Restore to run `opkg update' to detect opkg command.

diff --git a/ss+dnsmasq+dnscrypt b/ss+dnsmasq+dnscrypt
--- a/ss+dnsmasq+dnscrypt
+++ b/ss+dnsmasq+dnscrypt
@@ -37,7 +37,8 @@ deploy_start
 # 如果第一次运行本脚本, 请务必初始化 entware 包管理系统.
 # ssh 登陆路由器, 执行 entware-setup.sh, 选择 1'
 
-if ! opkg --version; then
+if ! opkg update; then
+    echo "Run \`opkg update' failed."
     echo "Run \`entware-setup.sh' to initalize entware-ng!"
     exit
 fi
